[colors]
draw_bold_text_with_bright_colors = true


# Colors (Gruvbox dark)
[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

[font]
size = 14.0

# CommitMono Nerd Font
# https://www.nerdfonts.com/
[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux new-session -A -s main"]

[window]
decorations = "full"
startup_mode = "Maximized"

[window.padding]
x = 2
y = 0
