" reset vim  to vim-defaults
if &compatible          " only if not set before:
  set nocompatible      " use vim-defaults instead of vi-defaults (easier, more user friendly)
endif

" Helpers functions
function! StrTrim(txt)
  return substitute(a:txt, '^\n*\s*\(.\{-}\)\n*\s*$', '\1', '')
endfunction

" Plugins Manager
call plug#begin('~/.vim/plugged')
" Vundle manage
Plug 'gmarik/vundle'

" Main (mandatory) bundles
" ------------------------
Plug 'tpope/vim-sensible'       " Init vimrc by tpope
Plug 'bling/vim-airline'        " Powerline with colors
Plug 'sjl/vitality.vim'         " AutoReload
Plug 'ctrlpvim/ctrlp.vim'       " Ctrlp
Plug 'tpope/vim-vinegar'        " Ctrlp
Plug 'scrooloose/nerdcommenter' " the missing comment tool
Plug 'scrooloose/syntastic'     " Multi language checker
Plug 'romain-h/sparkling'
Plug 'tpope/vim-surround'       " Surrounder
" Plug 'jiangmiao/auto-pairs'
Plug 'vim-scripts/scratch.vim'  " Block note into buffer
Plug 'Shougo/neocomplcache.vim' " Autocompletion
Plug 'sdanielf/vim-stdtabs'     " Standard indentation matching language
Plug 'tpope/vim-fugitive'       " Git for git blame..
Plug 'bufkill.vim'              " Kill buffer :bd
Plug 'SirVer/ultisnips'         " Snippet solution for Vim
Plug 'Peeja/vim-cdo'            " Missing :cdo / :ldo
Plug 'takac/vim-hardtime'

" UI
" --
Plug 'w0ng/vim-hybrid'
Plug 'iplog/vim-popsicles'

" Nice to have but not required for you Jedi
" ------------------------------------------
Plug 'majutsushi/tagbar'               " IDE like navigator into methods
Plug 'nathanaelkane/vim-indent-guides' " Indentation guide <leader>ig
Plug 'skwp/greplace.vim'               " Replace into multifiles
Plug 'mattn/emmet-vim'                 " html tags
Plug 'tpope/vim-markdown'
Plug 'junegunn/vim-easy-align'

" Specific to projects
" --------------------
Plug 'mattn/gist-vim'
Plug 'mattn/webapi-vim'
Plug 'groenewege/vim-less'
Plug 'nono/vim-handlebars'
Plug 'othree/html5.vim'
Plug 'elzr/vim-json'
Plug 'heavenshell/vim-jsdoc'
Plug 'pangloss/vim-javascript'
Plug 'fatih/vim-go'
Plug 'mxw/vim-jsx'
Plug 'derekwyatt/vim-scala'
" Neovim
Plug 'benekastah/neomake'

call plug#end()            " required

filetype plugin on
filetype indent on
syntax on

" color settings (if terminal/gui supports it)
if $TERM =~ '256color'
  set t_Co=256
  " Disable Background Color Erase (BCE) so that color schemes
  " work properly when Vim is used inside tmux and GNU screen.
  " See also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=
elseif $TERM =~ '^xterm$'
  set t_Co=256
endif

if &t_Co > 2 || has("gui_running")
  syntax on          " enable colors
  set hlsearch       " highlight search (very useful!)
  set incsearch      " search incremently (search while typing)
endif

" display settings
set background=dark     " enable for dark terminals
set scrolloff=2         " 2 lines above/below cursor when scrolling
set number              " show line numbers
set showmatch           " show matching bracket (briefly jump)
set showmode            " show mode in status bar (insert/replace/...)
set showcmd             " show typed command in status bar
set ruler               " show cursor position in status bar
set title               " show file in titlebar
set wildmenu            " completion with menu
set wildmode=longest:full,full
set wildignore=*.o,*.obj,*.bak,*.exe,*.py[co],*.swp,*~,*.pyc,.svn,.git
set laststatus=2        " use 2 lines for the status bar
set matchtime=2         " show matching bracket for 0.2 seconds
set matchpairs+=<:>     " specially for html

" editor settings
set colorcolumn=80             " Colum lenght
set autoindent smartindent     " turn on auto/smart indenting
set smarttab                   " smart tab handling for indenting
set magic                      " change the way backslashes are used in search patterns
set backspace=indent,eol,start " Allow backspacing over everything in insert mode
set tabstop=2                  " number of spaces a tab counts for
set shiftwidth=2               " spaces for autoindents
set expandtab                  " turn a tabs into spaces
set undolevels=10000           " number of forgivable mistakes
set timeoutlen=3000
set fileformat=unix            " file mode is unix
set diffopt=filler,iwhite      " ignore all whitespace and sync
set relativenumber             " relative number (check auto switch into mapping)

set encoding=utf-8
set fileencoding=utf-8

" Trim trailing whitespace when saving a document
autocmd BufWritePre * :%s/\s\+$//e

"Better line wrapping
set wrap
set textwidth=80
set formatoptions=qrn1

"Enable code folding
set foldenable

" Search options
set ignorecase
set hlsearch
set incsearch
set showmatch
set smartcase           " but become case sensitive if you type uppercase characters

" system settings
set lazyredraw          " no redraws in macros
set confirm             " get a dialog when :q, :w, or :wq fails
set viminfo='20,\"500   " remember copy registers after quitting in the .viminfo file -- 20 jump links, regs up to 500 lines'
set hidden              " remember undo after quitting
set history=1000        " keep 1000 lines of command history
set mouse=a             " use mouse in all modes
set mousehide           " Hide mouse when typing
set splitright          " the new window is created on the right

" Backups
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set undodir=~/.vim/tmp/undo//     " undo files
set backup                        " enable backup
set backupcopy=yes                " auto mode bug with a watcher task

" auto file reloading
set autoread
if !has('gui_running')
  " working thanks to vitality plugin and `set -g focus-events on` in tmux conf
 autocmd FocusGained,BufEnter * :silent! checktime
endif

" Remove bell beeping
set vb
set noeb vb t_vb=

" Color Scheme
set cursorline          " Higlight the current line
silent! colorscheme hybrid

if executable('ag')
  set grepprg=ag\ --search-files\ --smart-case\ --nogroup\ --nocolor
  command -nargs=+ -complete=file -bar Ag silent! grep! <args>|botright cw|redraw!
  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l -f --nocolor -g ""'

  set grepprg=ag
  let g:grep_cmd_opts = '--line-numbers --noheading'
endif

" ==== Mappings ====================
" ==================================
" Disable useless and annoying keys
noremap Q <Nop>

nnoremap <Leader>p :CtrlPBuffer<CR>
nnoremap <Leader>T :CtrlPClearCache<CR>:CtrlP<CR>
" grep word under cursor
nnoremap <Leader>F :Ag <C-R><C-W><CR>
nnoremap <Leader>f :Ag<space>

vmap <Enter> <Plug>(EasyAlign)

"Shortcut for editing  vimrc file in a new tab
nmap <leader>ev :tabedit $MYVIMRC<cr>

" line number
nnoremap <silent><leader>n :set rnu! rnu? <cr>

:au FocusLost * :set number
:au FocusGained * :set relativenumber
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber
" Use <C-L> to clear the highlighting of :set hlsearch.
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :nohlsearch<CR><C-L>
endif

"----------------------
" Plugins configuration
"----------------------

" Airline
let g:airline_theme = 'dark'
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline#extensions#syntastic#enabled = 0

" Neocomplete
let g:neocomplcache_enable_at_startup = 1

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete colorcolumn=100
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

inoremap <expr><Tab> pumvisible() ? "\<C-n>" : "\<Tab>"

" Gist
let g:gist_post_private = 1
let g:gist_detect_filetype = 1

" UltiSnips
let g:UltiSnipsEditSplit="vertical"

autocmd BufNewFile,BufRead *{-spec,Spec,-test}.js set ft=javascript.jasmine
autocmd BufNewFile,BufRead *.scala set ft=scala

" JSX
let g:jsx_ext_required = 0


" handlebars templates
autocmd BufNewFile,BufRead *.hb set ft=handlebars

" Nerdcommenter
let NERDSpaceDelims = 1

" Hardtime
let g:hardtime_default_on = 1
let g:hardtime_showmsg = 1
let g:hardtime_maxcount = 2
let g:hardtime_ignore_quickfix = 1
let g:list_of_normal_keys = ["h", "j", "k", "l", "+", "<UP>", "<DOWN>", "<LEFT>", "<RIGHT>"]

" Syntastic
" let b:syntastic_javascript_eslint_exec = StrTrim(system('npm-which eslint'))
let g:syntastic_mode_map = {
    \ "mode": "active",
    \ "active_filetypes": [],
    \ "passive_filetypes": ["javascript"] }


" Source the vimrc file after saving it. This way, you don't have to reload Vim to see the changes.
if has("autocmd")
 augroup myvimrchooks
  au!
  autocmd bufwritepost .vimrc source ~/.vimrc
 augroup END
endif

" Clipper yank for tmux
nnoremap <leader>y :call system('nc localhost 8377', @0)<CR>

set clipboard=unnamed
" To see all leader mappings currently in use:
" grep -R leader .vimrc .vim/bundle | perl -pe 's/.+(<leader>\w+).+/\1/' | sort | uniq

if has("nvim")
  let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': []  }
  let g:neomake_javascript_enabled_makers = ['eslint']
  let g:neomake_error_sign = {
      \ 'text': '>>',
      \ 'texthl': 'ErrorMsg',
      \ }
  hi WarningMsg ctermbg=3 ctermfg=0
  let g:neomake_warning_sign = {
      \ 'text': '>>',
      \ 'texthl': 'WarningMsg',
      \ }

  autocmd! BufWritePost * Neomake
else
  let g:syntastic_javascript_checkers = ['eslint']
endif

