# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="romain"

# Plugin
plugins=(git osx themes rvm rake brew terminalapp vi-mode bower node npm tmux)

source $ZSH/oh-my-zsh.sh

# Use vim as the editor
export EDITOR=vim

# Custom vi keybinding
# shift-tab
if [[ -n $terminfo[kcbt] ]]; then
  bindkey "$terminfo[kcbt]" reverse-menu-complete
fi

# delete
if [[ -n $terminfo[kdch1] ]]; then
  bindkey          "$terminfo[kdch1]" delete-char
  bindkey -M vicmd "$terminfo[kdch1]" vi-delete-char
fi

# backspace (and <C-h>)
if [[ -n $terminfo[kbs] ]]; then
  bindkey          "$terminfo[kbs]" backward-delete-char
  bindkey -M vicmd "$terminfo[kbs]" backward-char
fi

bindkey           '^H' backward-delete-char
bindkey -M vicmd  '^H' backward-char

# Keep retro compat with incremental search
bindkey "^R" history-incremental-search-backward
# Kill the lag with [esc]...
export KEYTIMEOUT=1

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH

# CLANG osX ...
export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments

# Source custom env that will not be tracked
source $HOME/.env_custom

# iTerm
if [ -f ~/.iterm2_shell_integration.zsh ]; then
  source ~/.iterm2_shell_integration.zsh
fi

